Chat.Api/ViewModels/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace Chat.Api.ViewModels;

public class LoginModel
{
    [Required] public string Login { get; set; }

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; }
}

Chat.Api/ViewModels/RegisterModel.cs
using System.ComponentModel.DataAnnotations;

namespace Chat.Api.ViewModels;

public class RegisterModel
{
    [Required] public string Name { get; set; }

    [Required] public string Login { get; set; }

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; }
}

Chat.Api/ViewModels/RoomModel.cs
using System.ComponentModel.DataAnnotations;

namespace Chat.Api.ViewModels
{
    public class RoomModel
    {
        [Required] public string Title { get; set; }
    }
}

Chat.Api/Controllers/AccountController.cs
using Chat.Api.ViewModels;
using Chat.Domain;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Chat.Service.Interface;

namespace Chat.Api.Controllers
{
    [Route("/account")]
    public class AccountController : Controller
    {
        private readonly IUserService _userService;

        public AccountController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet("login")]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;

            return View();
        }

        [HttpPost("login")]
        public async Task<IActionResult> Login(LoginModel model, string returnUrl)
        {
            var user = await _userService.GetUserByLoginAndPassword(model.Login, model.Password);
            if (user != null)
            {
                await Authenticate(model.Login, user.Id);
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [HttpGet("register")]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost("register")]
        public async Task<IActionResult> Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userService.GetUserByLoginAndPassword(model.Login, model.Password);
                if (user == null)
                {
                    var userId = await _userService.CreateUser(new User() { Login = model.Login, Name = model.Name, Password = model.Password });

                    await Authenticate(model.Login, userId);

                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError("", "Некорректные логин и(или) пароль");
            }

            return View(model);
        }

        private async Task Authenticate(string userName, int userId)
        {
            var claims = new List<Claim>
        {
            new(ClaimsIdentity.DefaultNameClaimType, userName),
            new("UsedId", userId.ToString())
        };

            var id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType,
                ClaimsIdentity.DefaultRoleClaimType);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

        [HttpGet("logout")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Account");
        }
    }
}

Chat.Api/Controllers/HomeController.cs
using Chat.Api.Pages.Shared;
using Chat.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Chat.Api.Controllers;

[Route("home")]
public class HomeController : Controller
{
    private readonly IRoomService _roomService;

    public HomeController(IRoomService roomService)
    {
        _roomService = roomService;
    }

    [Authorize]
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        return View(new IndexModel(await _roomService.GetRooms()));
    }
}

Chat.Api/Controllers/MessageController.cs
using System.Net.WebSockets;
using System.Security.Claims;
using Chat.Service.Implementation;
using Chat.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static System.Net.Mime.MediaTypeNames;

namespace Chat.Api.Controllers;

[Authorize]
[Route("/api/messages")]
public class MessageController : Controller
{
    private readonly IMessageService _messageService;
    private readonly WebSocketHandler _webSocketHandler;

    public MessageController(IMessageService messageService, WebSocketHandler webSocketHandler)
    {
        _messageService = messageService;
        _webSocketHandler = webSocketHandler;
    }

    [Authorize]
    [HttpGet("chat/{roomId}")]
    public async Task<IActionResult> CreateMessage([FromRoute] int roomId)
    {
        if (HttpContext.WebSockets.IsWebSocketRequest)
        {
            var socket = await HttpContext.WebSockets.AcceptWebSocketAsync();
            var ident = HttpContext.User.Identity as ClaimsIdentity;
            var username = ident.Name;
            await _webSocketHandler.OnConnectedAsync(socket, int.Parse(ident.Claims.ToArray()[1].Value), roomId, username);
        }
        else
        {
            HttpContext.Response.StatusCode = 400;
        }
        return View(await _messageService.GetMessagesByRoomId(roomId));
    }
}

Chat.Api/Controllers/RoomController.cs
using Chat.Api.Pages.Shared;
using Chat.Api.ViewModels;
using Chat.Domain;
using Chat.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Chat.Api.Controllers;

[Authorize]
[Route("/api/rooms")]
public class RoomController : Controller
{
    private readonly IRoomService _roomService;

    public RoomController(IRoomService roomService)
    {
        _roomService = roomService;
    }

    [Authorize]
    [HttpGet("index")]
    public async Task<IActionResult> Index()
    {
        return View(new Pages.Shared.IndexModel(await _roomService.GetRooms()));
    }

    [Authorize]
    [HttpGet("create")]
    public IActionResult Create()
    {
        return View();
    }

    [Authorize]
    [HttpPost("create")]
    public async Task<IActionResult> Store(RoomModel room)
    {
        await _roomService.CreateRoom(new Room() { Title = room.Title});

        return RedirectToAction("Index", "Home");
    }
}

Chat.Api/Controllers/UserController.cs
using System.Globalization;
using System.Security.Claims;
using Chat.Api.ViewModels;
using Chat.Domain;
using Chat.Service.Interface;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace Chat.Api.Controllers;

[Route("/api/users")]
public class UserController : Controller
{
    private readonly IUserService _userService;

    public UserController(IUserService userService)
    {
        _userService = userService;
    }

    [HttpGet]
    public async Task<IEnumerable<User>> Get()
    {
        return await _userService.GetUsers();
    }

    [HttpGet("{id}")]
    public async Task<User> Get(int id)
    {
        return await _userService.GetUserById(id);
    }

    [HttpDelete("{id}")]
    public async Task<int> Delete(int id)
    {
        return await _userService.DeleteUserById(id);
    }

    [HttpPut]
    public async Task<int> Update(User user)
    {
        return await _userService.UpdateUser(user);
    }
}

Chat.Api/Pages/Shared/Index.cshtml.cs
using Chat.Domain;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chat.Api.Pages.Shared;

public class IndexModel : PageModel
{
    public IndexModel(IEnumerable<Room> rooms)
    {
        Rooms = rooms.ToList();
    }

    public static List<Room> Rooms { get; set; } = new();

    public void OnGet()
    {
    }
}

Chat.Api/Pages/Shared/Index.cshtml
@page
@using Chat.Api.Pages.Shared
@model Chat.Api.Pages.Shared.IndexModel

@{

}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Чат-комнаты</title>
    <style>
            /* Общие стили */
            * {
                box-sizing: border-box;
                font-family: Arial, sans-serif;
            }

            body {
                background-color: #f2f2f2;
            }

            /* Стили списка комнат */
            .room-list {
                max-width: 500px;
                margin: 50px auto;
                background-color: #fff;
                padding: 20px;
                border-radius: 5px;
                box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            }

            .room-list h2 {
                text-align: center;
                margin-bottom: 20px;
            }

            .room-list ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
            }

            .room-list ul li {
                border-bottom: 1px solid #ccc;
                padding: 12px;
                display: flex;
                justify-content: space-between;
                align-items: center;
            }

            .room-list ul li:last-child {
                border-bottom: none;
            }

            .room-list ul li a {
                text-decoration: none;
                color: #000;
            }

            .room-list ul li a:hover {
                color: #2E8B57;
            }

            .join-button {
                background-color: #4CAF50;
                color: white;
                border: none;
                border-radius: 4px;
                cursor: pointer;
                padding: 8px 16px;
                font-size: 14px;
            }

            .join-button:hover {
                background-color: #45a049;
            }
    </style>
</head>
<body>
    <div class="room-list">
        <h2>Чат-комнаты</h2>
        <ul>
            @foreach (var chatRoom in IndexModel.Rooms)
            {
                <li>
                    <h4>@chatRoom.Title</h4>
                    <span>Количество участников: @chatRoom.Users.Count</span>
                    <button class="join-button">Присоединиться</button>
                </li>
            }
        </ul>
    </div>
</body>
</html>
@*
<p>
    <a asp-page="Index">Чат-комнаты</a>
</p>
<div>
    @foreach (var chatRoom in IndexModel.Rooms)
    {
        <div>
            <h4>@chatRoom.Title</h4>
            <span>Количество участников: @chatRoom.Users.Count</span>
            <button>Присоединиться</button>
        </div>
    }
</div>*@

Chat.Api/Views/Home/Index.cshtml
@page
@using Chat.Api.Pages.Shared
@model Chat.Api.Pages.Shared.IndexModel

@{

}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Чат-комнаты</title>
    <style>
        /* Общие стили */
        * {
            box-sizing: border-box;
            font-family: Arial, sans-serif;
        }

        body {
            background-color: #f2f2f2;
        }

        /* Стили списка комнат */
        .room-list {
            max-width: 500px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

            .room-list h2 {
                text-align: center;
                margin-bottom: 20px;
            }

            .room-list ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
            }

                .room-list ul li {
                    border-bottom: 1px solid #ccc;
                    padding: 12px;
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                }

                    .room-list ul li:last-child {
                        border-bottom: none;
                    }

                    .room-list ul li a {
                        text-decoration: none;
                        color: #000;
                    }

                        .room-list ul li a:hover {
                            color: #2E8B57;
                        }

        .join-button {
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            padding: 8px 16px;
            font-size: 14px;
        }

            .join-button:hover {
                background-color: #45a049;
            }
    </style>
</head>
<body>
    <div class="room-list">
        <h2>Чат-комнаты</h2>

        <ul>
            @foreach (var chatRoom in IndexModel.Rooms)
            {
                <li>
                    <h4>@chatRoom.Title</h4>
                    <span>Количество участников: @chatRoom.Users.Count</span>
                    <button class="join-button" onclick="location.href='@Url.Action("CreateMessage","Message", new { roomId = chatRoom.Id })'">Присоединиться</button>
                </li>
            }
        </ul>
        <button class="join-button"  type="button" onclick="location.href='@Url.Action("create","Room")'">
            Создать комнату
        </button>
    </div>
</body>
</html>

Chat.Api/Views/Message/CreateMessage.cshtml
@using Chat.Domain
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Chat App</title>
        <style>
            body {
                margin: 0;
                padding: 0;
                background-color: #f6f6f6;
                font-family: Arial, sans-serif;
            }

            .header {
                display: flex;
                justify-content: space-between;
                align-items: center;
                padding: 10px;
                background-color: #000;
                color: #fff;
            }

                .header h1 {
                    margin: 0;
                }

            .message-container {
                margin: 10px;
                overflow: auto;
            }

            .message-box {
                display: flex;
                margin-bottom: 10px;
                background-color: #fff;
                border-radius: 5px;
                padding: 10px;
            }

                .message-box p {
                    margin: 0;
                }

                .message-box .user {
                    color: #000;
                    font-weight: bold;
                    margin-right: 10px;
                }

            .messages {
                display: flex;
                justify-content: space-between;
                padding: 10px;
                background-color: #eee;
                bottom: 0;
                position: fixed;
                width: 100%;
            }

                .messages input {
                    flex: 1;
                    margin-right: 10px;
                    padding: 10px;
                    font-size: 16px;
                    border: none;
                    border-radius: 5px;
                    outline: none;
                }

            #sendmessage {
                    display: inline-block;
                    padding: 8px 20px;
                    background-color: #44c767;
                    color: #ffffff;
                    text-align: center;
                    font-size: 18px;
                    font-weight: bold;
                    border-radius: 5px;
                    border: none;
                    cursor: pointer;
                    box-shadow: 0px 4px #2e5d6d;
                    transition: box-shadow 0.3s ease-in-out;
                }

                #sendmessage:hover {
                    background-color: #5cbf2a;
                    box-shadow: 0px 4px #3d8a10;
            }
        </style>
    </head>
    <body>
        <div id="message-container" class="message-container">
            @foreach (var message in (IEnumerable<Message>)Model)
            {
                <div class="message-box">
                    <p>
                        <span class="user">@message.User.Login</span>
                        @message.Text
                    </p>
                </div>
            }
        </div>

    <div class="messages">
        <input type="text" id="messageTextInput" type="text" placeholder="Type your message here..." />
        <input id="sendmessage" type="button" value="Send"></input>
    </div>
        
    <script>
            let url = window.location.href;
            var socket = new WebSocket(url.replace("https", "wss"));
            socket.onopen = function (event) {
                console.log("WebSocket opened.");
            };
            socket.onmessage = function (event) {
                console.log("WebSocket message received:", event.data);
                let data = JSON.parse(event.data);
                let messages = document.getElementById("messages");
                let messages1 = document.getElementById("message-container");

                var messageBox = document.createElement("div");
                messageBox.classList.add("message-box");
                var messageText = document.createTextNode(data.message);
                var userName = document.createElement(data.username);
                userName.classList.add("user");
                userName.textContent = data.username;
                var messageP = document.createElement("p");
                messageP.appendChild(userName);
                messageP.appendChild(messageText);
                messageBox.appendChild(messageP);

                messages1.appendChild(messageBox);
            };
            socket.onclose = function (event) {
                console.log("WebSocket closed.");
            };
            socket.onerror = function (error) {
                console.log('WebSocket error:', error);
            };

            document.getElementById("sendmessage").addEventListener("click", function () {
                let textElement = document.getElementById("messageTextInput");
                let text = textElement.value;
                socket.send(text);
                textElement.value = '';
            });
        </script>
    </body>
    </html>
}

Chat.Api/Views/Room/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <h2>Создать комнату</h2>
    <form method="post">
            <p>
                <label>Введите название комнаты: </label><br/>
                <input name="title"/>
            </p>
            <input type="submit" value="Отправить"/>
    </form>
}